apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-dags-pvc
  namespace: job-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
