apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: schedule-service
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
#      test
#      initContainers:
#        - name: wait-for-mysql
#          image: busybox
#          command: [ 'sh', '-c', 'until nc -z job-mysql 3306; do echo waiting for mysql...; sleep 2; done' ]
      containers:
        - name: schedule-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: shared-dag-volume
      volumes:
        - name: shared-dag-volume
          persistentVolumeClaim:
            claimName: schedule-dags-pvc
