apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-dags-pvc
  namespace: schedule-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
