replicaCount: 1

image:
  repository: k12s101ss/notification-service
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

envFromSecret: notification-service-secret

ingress:
  enabled: true
  host: k12s101.p.ssafy.io
  path: /api/storage
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: traefik
