replicaCount: 1

image:
  repository: k12s101ss/agent-service
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

envFromSecret: agent-service-secret

ingress:
  enabled: true
  host: k12s101.p.ssafy.io
  path: /api/agent
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: traefik
