apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
spec:
  forwardAuth:
    address: http://auth-service.auth-service.svc.cluster.local:8080/api/auth/ping
    trustForwardHeader: true
    authResponseHeaders:
      - "X-User-Id"
