replicaCount: 1

image:
  repository: k12s101ss/react
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: k12s101.p.ssafy.io
      paths:
        - path: /
          pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: traefik

resources: {}
